- name: rsync deploy
  id: deploy
  uses: Pendect/action-rsyncer@v1.1.0
  env:
    DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
  with:
    flags: '-avzPs'
    options: ''
    ssh_options: ''
    src: '.'
    dest: 'root@pond.computer:/var/www/pond'

- name: Display status from deploy
  run: echo "${{ steps.deploy.outputs.status }}"
